repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    exclude: frontend/package-lock.json
  - id: mixed-line-ending
  - id: no-commit-to-branch
    args: [--branch, main]
- repo: local
  hooks:
  - id: go-unit-tests
    name: go unit tests
    entry: go test ./pkg/test/unit_test
    pass_filenames: false
    types: [go]
    language: system
    always_run: true
- repo: https://github.com/petalmd/dockerfile-pre-commit
  rev: 'v1.0'
  hooks:
  - id: dockerlint
