version: '3'

services:
  howarethey:
    container_name: howarethey
    image: kalmonipa/howarethey:v0.20
    restart: always
    environment:
        # Defines which service to send notifications too
      - NOTIFICATION_SERVICE=DISCORD
        # Discord Webhook to send notifications too. Read the discord webhook docs to get one
      - WEBHOOK_URL=https://discord.com/api/webhooks/myexamplewebhook
        # Picks a friend at 7am every Monday UTC
      - CRON=0 7 * * 1
    ports:
      # The Web UI
      - "8080:8080"
    volumes:
      # Define where your persistent storage goes too
      - path/to/sql/dir:/home/hat/sql
      - path/to/logs/dir:/home/hat/logs
