version: '3'

services:
  howarethey:
    container_name: howarethey
    image: kalmonipa/howarethey:v0.20
    restart: always
    environment:
        # Defines which service to send notifications too
      - NOTIFICATION_SERVICE=DISCORD
        # Discord Webhook to send notifications too. Read the discord webhook docs to get one
      - WEBHOOK_URL=https://discord.com/api/webhooks/myexamplewebhook
        # Picks a friend at 7am every Monday UTC
      - FRIEND_SELECTOR_CRON_SCHEDULE=0 7 * * 1
        # Defines what time of day in 24 hour time to notify of any birthdays
      - BIRTHDAY_CHECK_TIME=8
        # Explicitly tells the app the check for birthdays (defaults to `false` so this can be omitted)
      - IGNORE_BIRTHDAYS=false
    ports:
      # The Web UI
      - "8080:8080"
    volumes:
      # Define where your persistent storage goes too
      - path/to/sql/dir:/home/hat/sql
      - path/to/logs/dir:/home/hat/logs
