version: '3'

services:
  howarethey:
    container_name: howarethey
    image: kalmonipa/howarethey:v0.7
    environment:
        # Discord Webhook to send notifications too. Read the discord webhook docs to get one
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/myexamplewebhook
        # Picks a friend at 7am every Monday
      - CRON="0 7 * * MON"
    ports:
      # The Web UI (enabled by --api.insecure=true)
      - "8022:8080"
    volumes:
        # Define where your persistent storage goes too
      - ./sql/friend.db:/sql/friends.db
