version: '3'

services:
  # Backend Golang app running the API
  backend:
    container_name: howarethey-backend
    image: kalmonipa/howarethey-backend:v0.13
    restart: always
    ports:
      - "8080:8080"
    volumes:
     - $PWD/backend/sql/:/root/sql/
    networks:
      - howarethey-network
  # Frontend React app
  frontend:
    container_name: howarethey-frontend
    image: kalmonipa/howarethey-frontend:v0.13
    restart: always
    ports:
      - "3000:3000"
    networks:
      - howarethey-network

networks:
  howarethey-network:
    driver: bridge
    external: true
    name: howarethey-network
