version: '3'

services:
  howarethey:
    container_name: howarethey-backend
    image: kalmonipa/howarethey
    restart: always
    environment:
        # Discord Webhook to send notifications too. Read the discord webhook docs to get one
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/myexamplewebhook
        # Picks a friend at 7am every Monday
      - CRON=0 0 7 * * 1
    ports:
      # The Web UI (enabled by --api.insecure=true)
      - "8022:8080"
    volumes:
        # Define where your persistent storage goes too
      - ./sql/friend.db:/sql/friends.db
